### ISSUE TITLE
Failure parsing `#EXTINF`

### ISSUE THREAD

**Issue by elv-gilles** [ingest/manifest#15]
Parsing the following line fails with index out of bounds:
```
#EXTINF:2.002002
```
According to the definition of [EXTINF](https://tools.ietf.org/html/rfc8216#section-4.3.2.1), the title is optional and therefore the line is legal.

Fix in `decode-util.go`:

```
func decodeInf(line string) (*Inf, error) {
	var err error
	i := &Inf{}
	index := strings.Index(line, ",")
	if index < 0 {
		index = len(line)
	}
	if i.Duration, err = strconv.ParseFloat(line[0:index], 64); err != nil {
		return nil, err
	}
	if index+1 < len(line) {
		i.Title = line[index+1 : len(line)]
	}
	return i, err
}
```

**Comment by bradleyfalzon** [comment]
The comma isn’t optional though:

The remainder of the line following the comma is an optional human-readable informative title

See examples: https://tools.ietf.org/html/rfc8216#section-8

**Comment by elv-gilles** [comment]
Yep, you're right. 
That's annoying since the server i work with does not return the comma, but .. it should be there.

Probably best to close unless you'd like to make the parser lenient ?

**Comment by itsjamie** [comment]
What server if you don't mind answering, if it's a commercial or open-source one, perhaps we could upstream the fix.

I'll look around at a few other produced manifests and see how many are missing the `,`.

**Comment by elv-gilles** [comment]
I could talk to the server team, they're fixing the generation of EXTINF.

Yet your looking at others might still be valuable since no other tool was failing ..

**Comment by itsjamie** [comment]
Yeah, I've looked at the hls.js m3u8 parser code, and it uses a regex that marks the comma optional. However, I looked at encoding.com, Shaka packager, and Bitmovin produced HLS manifests and they all include the comma.

I'll keep this in mind if we add a lenient parsing mode, but I'd prefer to expect well-formed manifests.

Thanks for the report @elv-gilles, I'll add an error to the parsing if no comma is found so that it doesn't cause an index out of bounds error.
